const EMOTIONS: ISubemotion = {
	MEDO: ["MEDO","TIMIDEZ","RECEIO","APREENSÃO","TEMOR","NERVOSISMO","ANSIEDADE","INSEGURANÇA","PÂNICO","DESESPERO", "HORROR","TERROR"],
	ALEGRIA: ["ALEGRIA", "CALMARIA", "ALÍVIO","COMPAIXÃO","ADMIRAÇÃO","ORGULHO","PRAZER","TRIUNFO","FELICIDADE","DIVERSÃO","BRINCALHÃO","MARAVILHADO","ENTUSIASMO","EMPOLGAÇÃO","EUFORIA","MOTIVADO"],
	TRISTEZA: ["TRISTEZA","DESAPONTAMENTO","DESÂNIMO","AGITAÇÃO","IMPOTÊNCIA","MÁGOA","DESESPERANÇA","PESAR","DESESPERO","DESMOTIVADO","SOLIDÃO","ANSIEDADE","ANGÚSTIA","SOFRIMENTO","DEPRESSIVO","MELANCOLIA"],
	RAIVA: ["RAIVA","INCÔMODO","IRRITAÇÃO","FRUSTRAÇÃO","DESGOSTO","REVOLTA","RESSENTIMENTO","AMARGURA","ANSIEDADE","HOSTILIDADE","VINGATIVO","FÚRIA","AGRESSIVO"],
	NOJO: ["NOJO", "AVERSÃO", "NÁUSEA", "REPULSA", "ASCO", "DESGOSTO", "REPUGNÂNCIA"],
	SURPRESA: ["SURPRESA","DESCONFORTO","ADORAÇÃO", "FRUSTRAÇÃO", "CHOQUE", "ANSIEDADE", "CONFUSÃO", "SUSTO"],
	SOCIAL: ["JULGADO", "SAUDOSO", "EXCITADO", "AMOR", "INVEJA", "PENSATIVO", "APATIA", "COMPULSÃO", "TENSÃO", "DESPREZO", "ADMIRAÇÃO", "SIMPATIA", "CONSTRANGIMENTO", "CIÚMES", "CULPA", "VERGONHA", "EMPATIA", "ÓDIO", "NOSTALGIA", "DESEJO SEXUAL", "PAZ"]
};

// enum SUBEMOTIONS {
//     MEDO = "MEDO",
// 	ALEGRIA = "ALEGRIA",
// 	TRISTEZA = "TRISTEZA",
// 	RAIVA = "RAIVA",
// 	NOJO = "NOJO",
// 	SURPRESA = "SURPRESA",
// 	SOCIAL = "SOCIAL"
// }

interface ISubemotion {
    MEDO: string[],
    ALEGRIA: string[],
	TRISTEZA: string[],
	RAIVA: string[],
	NOJO: string[],
	SURPRESA: string[],
	SOCIAL: string[]
}

const THOUGHTS = [
	"FAMÍLIA",
	"TRABALHO",
	"ROMANCE",
	"SOCIAL",
	"AMIZADE",
	"ESTUDO",
	"DINHEIRO",
	"SAÚDE FÍSICA",
	"SAÚDE MENTAL",
	"OUTROS"
];


const MacroOptions  = {
	EMOTIONS,
	THOUGHTS,
};

const MicroOptions = {
	... EMOTIONS
};

export const OptionsTypes =  {
	... MacroOptions,
	...MicroOptions
};

